//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterDetailsPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateOrder
    {
        public int OrderID { get; set; }
        public string CategoryName { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public int Quantity { get; set; }
    }
}
